#!/bin/bash
#
# description: Hooker Application Upstart, using Forever


APPHOME=/var/www/general/hooker
APPSCRIPT=index.js

PATH=/usr/bin:/sbin:/bin:/usr/sbin
export PATH

# Source function library.
. /etc/rc.d/init.d/functions

start() {
    echo -n $"Starting sample-app agent: "
    cd "$APPHOME" && ./forever start "$APPSCRIPT"
    echo
}

stop() {
    echo -n $"Stopping sample-app agent: "
    cd "$APPHOME" && ./forever stop "$APPSCRIPT"
    echo
}

reload() {
    echo -n $"Restarting sample-app agent: "
    cd "$APPHOME" && ./forever start "$APPSCRIPT"
    echo
}

status() {
    cd "$APPHOME" && ./forever list
}

restart() {
    reload
}

case "$1" in
    start)
        start
    ;;
    stop)
        stop
    ;;
    restart|reload|force-reload)
        reload
    ;;
    status)
        status
    ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart|reload|force-reload"
        exit 1
esac

exit $RETVAL
